/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'section',
    'music-card',
    'bg-pastelBlue',
    'bg-pastelPurple',
    'bg-pastelPink',
    'bg-pastelGreen',
    'bg-pastelYellow',
    'from-pastelBlue',
    'from-pastelPurple',
    'from-pastelPink',
    'from-pastelGreen',
    'from-pastelYellow',
    'to-pastelBlue',
    'to-pastelPurple',
    'to-pastelPink',
    'to-pastelGreen',
    'to-pastelYellow',
    'rounded-3xl',
    'rounded-2xl',
    'rounded-xl',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'backdrop-blur-md',
    'backdrop-blur-xl',
    'border-pastelPurple',
    'border-pastelPurple/30',
    'border-pastelPurple/40',
    'border-pastelPurple/60',
    'text-pastelBlue',
    'text-pastelPurple',
    'text-pastelPink',
    'text-pastelGreen',
    'text-pastelYellow',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'muted-pastel': 'linear-gradient(135deg, #e0e7ff 0%, #f3e8ff 100%)',
        'muted-pink': 'linear-gradient(135deg, #ffe0f0 0%, #e0e7ff 100%)',
        'muted-green': 'linear-gradient(135deg, #d1fae5 0%, #e0f2fe 100%)',
      },
      colors: {
        pastelBlue: '#e0e7ff',
        pastelPurple: '#f3e8ff',
        pastelPink: '#ffe0f0',
        pastelGreen: '#d1fae5',
        pastelYellow: '#fef9c3',
        mutedGray: '#f3f4f6',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans KR', 'Pretendard', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
} 