server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chordmind}
    username: ${DB_USER:chordmind_user}
    password: ${DB_PASSWORD:chordmind_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin}

jwt:
  secret: ${JWT_SECRET:chordmind-jwt-secret-key-2024-very-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.chordmind: ${LOGGING_LEVEL_COM_CHORDMIND:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:DEBUG} 