server:
  port: 8081

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/chordmind_user
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: chordmind-jwt-secret-key-2024-very-long-and-secure
  expiration: 86400000 # 24시간

logging:
  level:
    com.chordmind: DEBUG
    org.springframework.security: DEBUG 