services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chordmind
      POSTGRES_USER: chordmind
      POSTGRES_PASSWORD: chordmind123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - redis
      - user-service
      - practice-service
      - harmony-service
      - ai-service

  practice-service:
    build:
      context: ./backend/practice-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chordmind
      SPRING_DATASOURCE_USERNAME: chordmind
      SPRING_DATASOURCE_PASSWORD: chordmind123
    depends_on:
      - postgres

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8083
      SPRING_APPLICATION_NAME: user-service
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chordmind_user
      DB_USER: chordmind
      DB_PASSWORD: chordmind123
      JWT_SECRET: chordmind-jwt-secret-key-2024-very-long-and-secure
      JWT_EXPIRATION: 86400000
      SECURITY_USER_NAME: admin
      SECURITY_USER_PASSWORD: admin
      LOGGING_LEVEL_COM_CHORDMIND: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    depends_on:
      - postgres

  harmony-service:
    build:
      context: ./backend/harmony-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chordmind
      SPRING_DATASOURCE_USERNAME: chordmind
      SPRING_DATASOURCE_PASSWORD: chordmind123
    depends_on:
      - postgres

  ai-service:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      AI_SERVICE_URL: http://ai-service:8082
      HARMONY_SERVICE_URL: http://harmony-service:8084
      USER_SERVICE_URL: http://user-service:8083
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chordmind_ai
      DB_USER: chordmind
      DB_PASSWORD: chordmind123
    depends_on:
      - postgres

volumes:
  postgres_data: 