server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:harmony-service}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chordmind_harmony}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT 설정
jwt:
  secret: ${JWT_SECRET:chordmind-jwt-secret-key-2024-very-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000}

# AI 서비스 연동 설정
ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8088}
    timeout:
      connect: ${AI_SERVICE_CONNECT_TIMEOUT:10000}
      read: ${AI_SERVICE_READ_TIMEOUT:30000}

# 로깅 설정
logging:
  level:
    com.chordmind: ${LOGGING_LEVEL_COM_CHORDMIND:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:DEBUG} 